module.exports = {
    METHOD_GET: "GET",
    METHOD_POST: "POST",
    METHOD_PUT: "PUT",
    METHOD_DELETE: "DELETE",
    METHOD_HEAD: "HEAD",
    METHOD_CONNECT: "CONNECT",
    METHOD_OPTIONS: "OPTIONS",
    METHOD_TRACE: "TRACE",
    METHOD_PATCH: "PATCH",
};
